name: threadfon
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: 3.24.3

dependencies:
  # Annotation
  meta: any
  json_annotation: ^4.8.1

  # State management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

  # Database
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3

  # very_good_analysis: ^6.0.0
  sqflite_common_ffi: ^2.3.3

  intl: any
  async: any
  path: any
  collection: any

  convert: any

  google_fonts: ^6.2.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  # Architecture
  flex_color_scheme: ^7.3.1

  # localization
  flutter_localizations:
    sdk: flutter


  # for UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  salomon_bottom_bar: ^3.3.2


  freezed_annotation: ^2.4.4

  # for info
  logger: ^2.4.0

  path_provider: ^2.1.4
  url_launcher: ^6.3.0



dev_dependencies:
  intl_utils: ^2.8.7
  build_runner: ^2.4.12
  json_serializable:
    ^6.8.0

  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.7.0
  # Linting
  flutter_lints: ^3.0.2
  freezed: ^2.5.7

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/db/
    - assets/svg/
    - assets/images/
    - assets/images/type_thread/
    - assets/images/m_thread/

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/common/localization
  output_dir: lib/src/common/localization/generated
  use_deferred_loading: false

flutter_gen:
  output: lib/src/common/constant/
  line_length: 120
  #
