name: Flutter Build APK

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decrypt files
        run: |
          mkdir -p android/app
          # Расшифровка keystore файла
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.FILE_PASSPHRASE }}" \
          --output android/app/keystore.jks android/app/keystore.jks.gpg
          
          # Расшифровка env_dart/prod.json.gpg
          mkdir -p env_dart
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.FILE_PASSPHRASE }}" \
          --output env_dart/prod.json env_dart/prod.json.gpg
          
          # Расшифровка google-services.json.gpg
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.FILE_PASSPHRASE }}" \
          --output android/app/google-services.json android/app/google-services.json.gpg

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2"
          channel: "stable"
          cache: true

      - name: Flutter pub get
        run: flutter pub get
        
      - name: Generate code with build_runner
        run: dart run build_runner build --delete-conflicting-outputs --release

      - name: Build APK
        run: flutter build apk --release --dart-define-from-file=env_dart/prod.json
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Get commit info
        id: commit-info
        run: |
          echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "date=$(git log -1 --format=%cd --date=format:'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Upload APK to release folder
        id: upload-release
        run: |
          # Создаем папку для релизов, если её нет
          mkdir -p releases
          # Копируем APK в папку releases с именем, содержащим commit hash
          cp build/app/outputs/flutter-apk/app-release.apk releases/app-${{ steps.commit-info.outputs.sha }}.apk
          # Устанавливаем имя файла для использования в дальнейших шагах
          echo "filename=app-${{ steps.commit-info.outputs.sha }}.apk" >> $GITHUB_OUTPUT

      - name: Send Telegram notification with APK
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚀 Новая сборка приложения
            
            Repo: ${{ github.repository }}
            Commit: ${{ steps.commit-info.outputs.sha }}
            Дата: ${{ steps.commit-info.outputs.date }}
            Сообщение: ${{ steps.commit-info.outputs.message }}
          document: build/app/outputs/flutter-apk/app-release.apk